version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:${PORT}"
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db: