version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:${PORT}"
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    