version: '3'
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - APP_ENV=prod
    command: npm run start